include: ['_pages', '_data', 'js','_directory']
timezone: America/Chicago
siteurl: https://scoutrec.com
name: Scout Real Estate Co.
url: "https://scoutrec.com"
favicon: /assets/img/favicon/favicon.ico
google_analytics: G-RYWPLKMTQR
logo_image: /assets/svg/logos/SCOUT-WEBSITE-MAIN-LOGO (1).png
social:
  name: Scout Real Estate Co.
  links:
  - https://instagram.com/scoutrealestateco
  - https://facebook.com/scoutrealestateco
  - https://www.youtube.com/channel/UCnEJTuCvF082zAAjpeasQIA
  - https://www.linkedin.com/company/scout-real-estate-co/
  - /directory
plugins:
  - jekyll-feed
permalink: /:title
# Jekyll Feed settings
feed_items: 20
feed_update_period: weekly
feed_update_frequency: 1

algolia:
  application_id: 'SZ1NFM42A3'
  index_name: 'scout'
  search_only_api_key: 'c7f2201fd5f842587c801eb1a87e88a2'
defaults:
-scope:
  path: ""
  values:
    layout: default
    _options:
      content: &content_defaults
        uploads_dir: "uploads/:title"
        format: p h1 h2 h3 h4 h5 h6 div
        styles: /assets/css/theme.css
        undo: true
        redo: true
        left: text-left
        center: text-center
        right: text-right
        justify: justify-content-center
        bold: true
        italic: true
        underline: true
        strike: true
        subscript: false
        superscript: false
        blockquote: true
        table: true
        copyformatting: true
        removeformat: true
        numberedlist: true
        bulletedlist: true
        outdent: false
        indent: false
        image: true
        link: true
        embed: true
collections:
 properties:
   output: true
 directory:
   output: true
   custom_permalink_placeholders: ["type"]
   permalink: directory/:type/:title/
-scope:
      type: pages
      path: _pages/index.html
      values:
        permalink:
-scope:
   path: "_directory"
   type: "page"
   values:
   layout: "listing"
_structures:
  sub_text:
    type: text
    label: Secondary text
    comment: Appears at the bellow title in banner
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-algolia
  - jekyll_custom_permalink
# Excluded items can be processed by explicitly listing the directories or
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
